# Generated by Django 5.2 on 2025-04-13 14:04

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventor',
            fields=[
                ('Inventor_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('preferred_name', models.CharField(max_length=150)),
                ('name_variants', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, null=True, size=None)),
                ('email', models.EmailField(default=None, max_length=254, unique=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='inventors/images/')),
                ('orcid', models.CharField(blank=True, default=None, max_length=19, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, default=None, max_length=11, null=True)),
                ('affiliation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventors.affiliation')),
            ],
        ),
    ]
