# Generated by Django 5.2 on 2025-04-16 07:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('parent_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventor',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('preferred_name', models.CharField(max_length=150)),
                ('name_variants', models.TextField(blank=True, null=True)),
                ('affiliation', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('image', models.CharField(blank=True, max_length=300, null=True)),
                ('orcid', models.CharField(blank=True, max_length=19, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('password', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('deposit_number', models.BigIntegerField(unique=True)),
                ('deposit_document', models.CharField(max_length=255)),
                ('deposit_date', models.DateField()),
                ('research_report_document', models.CharField(max_length=255)),
                ('research_report_result', models.CharField(choices=[('A', 'MAI'), ('B', 'MR'), ('C', 'B1'), ('D', 'REFUSE')], default='A', max_length=1)),
                ('research_report_date', models.DateField()),
                ('delivery_document', models.CharField(max_length=255)),
                ('delivery_date', models.DateField()),
                ('status', models.CharField(choices=[('A', 'A1'), ('B', 'B1')], default='A', max_length=1)),
                ('TRL_level', models.BigIntegerField(blank=True, null=True)),
                ('CRL_level', models.BigIntegerField(blank=True, null=True)),
                ('abstract', models.TextField()),
                ('contract_type', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C')], default='A', max_length=1)),
                ('sector', models.CharField(choices=[('L', 'Telecommunications'), ('I', 'Healthcare & Pharmaceuticals'), ('A', 'Aerospace & Defense'), ('E', 'Chemicals & Materials'), ('B', 'Agriculture'), ('G', 'Electronics'), ('K', 'Manufacturing & Industrial Equipment'), ('J', 'Information Technology & Software'), ('F', 'Consumer Goods'), ('D', 'Biotechnology'), ('H', 'Energy & Renewables'), ('C', 'Automotive & Transportation')], default='A', max_length=1)),
                ('nature', models.CharField(choices=[('A', 'METHOD'), ('B', 'SYSTEM'), ('C', 'PRODUCT'), ('D', 'DEVICE'), ('E', 'MATERIAL')], default='A', max_length=1)),
                ('schemas', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None)),
                ('affiliation', models.ManyToManyField(blank=True, related_name='+', to='inventors.affiliation')),
                ('inventors', models.ManyToManyField(related_name='+', to='inventors.inventor')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=255)),
                ('context', models.TextField()),
                ('problem_identification', models.TextField()),
                ('drawings', models.CharField(blank=True, max_length=255, null=True)),
                ('co_applications', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None)),
                ('status', models.CharField(max_length=255)),
                ('meeting_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventors', models.ManyToManyField(related_name='+', to='inventors.inventor')),
            ],
        ),
    ]
