# Generated by Django 5.2 on 2025-04-13 20:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventor',
            name='affiliation',
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=255)),
                ('context', models.TextField()),
                ('problem_identification', models.TextField()),
                ('drawings', models.CharField(blank=True, max_length=255, null=True)),
                ('co_applications', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None)),
                ('status', models.CharField(max_length=255)),
                ('meeting_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventors', models.ManyToManyField(related_name='+', to='inventors.inventor')),
            ],
        ),
        migrations.AddField(
            model_name='inventor',
            name='affiliation',
            field=models.ManyToManyField(blank=True, related_name='inventors', to='inventors.affiliation'),
        ),
    ]
