# Generated by Django 5.2 on 2025-04-13 21:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventors', '0002_remove_inventor_affiliation_ticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventor',
            name='affiliation',
            field=models.ManyToManyField(blank=True, related_name='+', to='inventors.affiliation'),
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('deposit_number', models.BigIntegerField(unique=True)),
                ('deposit_document', models.CharField(max_length=255)),
                ('deposit_date', models.DateField()),
                ('research_report_document', models.CharField(max_length=255)),
                ('research_report_result', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C')], default='A', max_length=1)),
                ('research_report_date', models.DateField()),
                ('delivery_document', models.CharField(max_length=255)),
                ('delivery_date', models.DateField()),
                ('status', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C')], default='A', max_length=1)),
                ('TRL_level', models.BigIntegerField(blank=True, null=True)),
                ('CRL_level', models.BigIntegerField(blank=True, null=True)),
                ('abstract', models.TextField()),
                ('contract_type', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C')], default='A', max_length=1)),
                ('sector', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C')], default='A', max_length=1)),
                ('nature', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C')], default='A', max_length=1)),
                ('schemas', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None)),
                ('affiliation', models.ManyToManyField(blank=True, related_name='+', to='inventors.affiliation')),
                ('inventors', models.ManyToManyField(related_name='+', to='inventors.inventor')),
            ],
        ),
    ]
