# Generated by Django 5.2 on 2025-04-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventors', '0002_remove_inventor_affiliation_ticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventor',
            name='affiliation',
            field=models.ManyToManyField(blank=True, related_name='+', to='inventors.affiliation'),
        ),
    ]
